In [2]:
import numpy as np

In [ ]:
# 1
v1 = np.linspace(1, 10, num=10)
print(v1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# 2
m1 = np.zeros((3, 3), dtype = int)
print(m1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# 3
import numpy as np

min = 1
max = 10

random_matrix = np.random.randint(min, max+1, size=(5, 5))

print(random_matrix)


[[ 2  3  7  5  3]
 [ 7  6  2  4  6]
 [ 5  6  5  2  9]
 [10  1  4  6  9]
 [ 4  1  6  6  9]]


In [ ]:
# 4
import numpy as np

random_matrix = np.random.rand(4, 4)

print(random_matrix)


In [ ]:
# 5
m1 = np.random.randint(1, 11, size=5)
m2 = np.random.randint(1, 11, size=5)
print(m1)
print(m2)
print(m1 + m2)
print(m1 - m2)
c = np.dot(m1, m2)
print(c)

In [ ]:
# 6
v1 = np.random.randint(1, 10, 7)
v2 = np.random.randint(1, 10, 7)
v3 = np.dot(v1, v2)
print(v1)
print(v2)
print(v3)

In [ ]:
# 7
m1 = np.random.randint(1,11, (2,2))
m2 = np.random.randint(1,11, (2,3))
m3 = np.dot(m1, m2)
print(m3)

[[ 7 11 26]
 [27 27 54]]


In [ ]:
# 8
m1 = np.random.randint(1, 11, (3,3))
print(m1)

m2 = np.linalg.inv(m1)
print(m2)

[[ 2  7  9]
 [ 6  4  6]
 [ 6  3 10]]
[[-0.12359551  0.24157303 -0.03370787]
 [ 0.13483146  0.19101124 -0.23595506]
 [ 0.03370787 -0.20224719  0.19101124]]


In [ ]:
# 9
m1 = np.random.random((4, 4))
print(m1)
print(50* '*')

m2 = m1.T
print(m2)

In [3]:
# 10
v1 = np.random.randint(1, 11, 4)
#print(v1)

m1 = np.random.randint(1, 11, (3,4))
#print(m1)

r = np.dot(m1, v1)
print(r)

[40 35 43]


In [ ]:
# 11
v1 = np.random.rand(3)
m1 = np.random.rand(2,3)
print(v1)
print(m1)
r = np.dot(m1, v1)
print(r)

In [10]:
# 12
m1 = np.random.randint(1, 11, (2,2))
m2 = np.random.randint(1, 11, (2,2))
print(m1 * m2)

[[10 24]
 [25  8]]


In [12]:
# 13
m1 = np.random.randint(1, 11, (2, 2))
m2 = np.random.randint(1, 11, (2, 2))
r = np.dot(m1, m2)
print(r)

[[ 80  38]
 [130  66]]


In [ ]:
# 14
m1 = np.random.randint(1, 101, (5, 5))
print(m1)
r = np.sum(m1)
print(r)

In [18]:
# 15
m1 = np.random.randint(1, 11, (4, 4))
m2 = np.random.randint(1, 11, (4, 4))
r = m1 = m2
print(r)

[[ 6  2 10  3]
 [ 9  2  6  1]
 [ 8  8  3  4]
 [ 5  8 10  4]]


In [20]:
# 16
# axis=1 вказує функції np.sum() обчислити суму елементів по рядках.
m1 = np.random.rand(1,11, (3, 3))
m_r = np.sum(m1, axis=1)
print(m_r)

[1.33049062 1.54420604 1.81135997]


In [24]:
# 17
m1 = np.random.randint(1, 11, (3, 4))
print(m1)
m_r = np.square(m1)
print(m_r)


[[ 5 10  8  3]
 [10  8  5  1]
 [ 9  6  3  2]]
[[ 25 100  64   9]
 [100  64  25   1]
 [ 81  36   9   4]]


In [26]:
# 18
v1 = np.random.randint(1, 50, 4)
print(v1)
v_r = np.sqrt(v1)
print(v_r)

[ 2 33 46 36]
[1.41421356 5.74456265 6.78232998 6.        ]
